cities:
  - Tokyo
  - London
  - New-York
  - Brisbane
  - Bristol
  - Manchester
  - Mumbai
  - Bangkok
  - Kuala-Lumpur
  - Singapore
  - Taipei
  - Shanghai
  - Hong-Kong
  - Berlin
  - Copenhagen
  - Paris
  - Dublin
  - Amsterdam
  - Barcelona
  - Glasgow
  - Stockholm
  - Oslo
  - Seattle
  - Seoul