[tool.poetry]
name = "server-side"
version = "0.1.0"
description = ""
authors = ["yo <yoichiojima@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
jpy-datareader = "^0.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
