name: Deploy client-side

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd client-side
          npm install

      - name: Build the app
        run: |
          cd client-side
          npm run build

      - name: Run tests
        run: |
          cd client-side
          npm test -- --watchAll=false

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' # Deploy only on push
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build